import React from "react";
import { service } from "@/services/index";

export const metadata = {
  title: "About Page",
  description: "Generated by create next app",
};

const aboutData = async () => {
  const response = await service.listDocuments("64edb591a9579d23f5be");
  return response;
};

async function About() {
  const aboutInfo = await aboutData();

  return (
    <div className="2xl:container 2xl:mx-auto lg:py-4 lg:px-20 md:py-12 md:px-6 px-4 bg-white">
      {aboutInfo.documents.map((item, id) => (
        <div className="flex lg:flex-row justify-between pt-12 pb-8" key={id}>
          <div className="w-full flex flex-col justify-center">
            <h1 className="text-3xl lg:text-4xl font-bold leading-9 text-gray-800 dark:text-white pb-4">
              {item.title}
            </h1>
            <p className="font-normal text-base leading-6 text-gray-600 dark:text-white">
              {item.description}
            </p>
          </div>
        </div>
      ))}
    </div>
  );
}

export default About;
